### ISSUE TITLE
Add functions to compute similarity of dynamics and proximity between two neural trajectories

### ISSUE THREAD

**Issue by kushaangupta** [ryanharvey1/neuro_py#35]
Refer: Guidera, J. A., Gramling, D. P., Comrie, A. E., Joshi, A., Denovellis, E. L., Lee, K. H., Zhou, J., Thompson, P., Hernandez, J., Yorita, A., Haque, R., Kirst, C., & Frank, L. M. (2024). Regional specialization manifests in the reliability of neural population codes. bioRxiv : the preprint server for biology, 2024.01.25.576941. https://doi.org/10.1101/2024.01.25.576941

**Comment by ryanharvey1** [comment]
do they have published code for this?
